addons:
  code_climate:
    repo_token: bcd161f57d21cacc61fd348f4f3b5a40599be17d2c82fbc81af08d5ef84909a4
dist: trusty
sudo: required
language: node_js
node_js:
  - "6"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_script:
  - sh -e /etc/init.d/xvfb start
  - npm install -g gulp
  - npm install -g bower
install:
  - npm install
script:
  - npm build
  - npm test
#  - npm run lint
#  - npm run test:once
#  - npm run e2e
  - npm run coverage
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
